<a href="https://colab.research.google.com/github/PranavPanure/ML-sem2/blob/main/Assignment_1_ML_53.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Pranav Bhushan Panure

Roll no: 53

Class: CSAI D

Prn: 12411151

kaggle dataset: https://www.kaggle.com/datasets/azminetoushikwasi/cr7-cristiano-ronaldo-all-club-goals-stats

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_csv = pd.read_csv("GoatData.csv")
df_csv.head()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN

In [ ]:
df_csv.tail(4)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
706,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,18,0:1,Penalty,\t
707,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,23,0:2,Left-footed shot,Sultan Al-Ghannam
708,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,44,0:3,Counter attack goal,Ayman Yahya
709,22/23,Saudi Pro League,21,3/18/23,H,Al-Nassr FC,Abha Club,2:1,CF,78,1:1,Direct free kick,NaN

In [ ]:
df_csv.index

RangeIndex(start=0, stop=710, step=1)

In [ ]:
df_csv.columns

Index(['Season', 'Competition', 'Matchday', 'Date', 'Venue', 'Club',
       'Opponent', 'Result', 'Playing_Position', 'Minute', 'At_score', 'Type',
       'Goal_assist'],
      dtype='object')

In [ ]:
df_csv.to_numpy()

array([['02/03', 'Liga Portugal', '6', ..., '2:00', 'Solo run', nan],
       ['02/03', 'Liga Portugal', '6', ..., '3:00', 'Header',
        'Rui Jorge'],
       ['02/03', 'Liga Portugal', '8', ..., '1:02', 'Right-footed shot',
        'Carlos Martins'],
       ...,
       ['22/23', 'Saudi Pro League', '18', ..., '0:2',
        'Left-footed shot', 'Sultan Al-Ghannam'],
       ['22/23', 'Saudi Pro League', '18', ..., '0:3',
        'Counter attack goal', 'Ayman Yahya'],
       ['22/23', 'Saudi Pro League', '21', ..., '1:1',
        'Direct free kick', nan]], dtype=object)

In [ ]:
df_csv.T

,0,1,2,3,4,5,6,7,8,9,...,700,701,702,703,704,705,706,707,708,709
Season,02/03,02/03,02/03,02/03,02/03,03/04,03/04,03/04,03/04,03/04,...,22/23,22/23,22/23,22/23,22/23,22/23,22/23,22/23,22/23,22/23
Competition,Liga Portugal,Liga Portugal,Liga Portugal,Taca de Portugal Placard,Taca de Portugal Placard,Premier League,FA Cup,Premier League,Premier League,Premier League,...,Europa League,Saudi Pro League,Saudi Pro League,Saudi Pro League,Saudi Pro League,Saudi Pro League,Saudi Pro League,Saudi Pro League,Saudi Pro League,Saudi Pro League
Matchday,6,6,8,Fourth Round,Fifth Round,11,Fifth Round,29,32,38,...,Group Stage,15,16,16,16,16,18,18,18,21
Date,10-07-02,10-07-02,10/26/02,11/24/02,12/18/02,11-01-03,2/14/04,3/20/04,04-10-04,5/15/04,...,10/27/22,2/3/23,2/9/23,2/9/23,2/9/23,2/9/23,2/25/23,2/25/23,2/25/23,3/18/23
Venue,H,H,A,H,H,H,H,H,A,A,...,H,A,A,A,A,A,A,A,A,H
Club,Sporting CP,Sporting CP,Sporting CP,Sporting CP,Sporting CP,Manchester United,Manchester United,Manchester United,Manchester United,Manchester United,...,Manchester United,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC,Al-Nassr FC
Opponent,Moreirense FC,Moreirense FC,Boavista FC,CD Estarreja,FC Oliveira do Hospital,Portsmouth FC,Manchester City,Tottenham Hotspur,Birmingham City,Aston Villa,...,FC Sheriff,Al-Fateh,Al-Wehda FC,Al-Wehda FC,Al-Wehda FC,Al-Wehda FC,Damac FC,Damac FC,Damac FC,Abha Club
Result,3:00,3:00,1:02,4:01,8:01,3:00,4:02,3:00,1:02,0:02,...,3:0,2:2,0:4,0:4,0:4,0:4,0:3,0:3,0:3,2:1
Playing_Position,LW,LW,NaN,NaN,NaN,RW,RW,NaN,NaN,NaN,...,CF,CF,CF,CF,CF,CF,CF,CF,CF,CF
Minute,34,90+5,88,67,13,80,74,89,60,4,...,81,90+3,21,40,53,61,18,23,44,78
At_score,2:00,3:00,1:02,3:00,3:00,2:00,3:00,2:00,1:01,0:01,...,3:0,2:2,0:1,0:2,0:3,0:4,0:1,0:2,0:3,1:1
Type,Solo run,Header,Right-footed shot,Left-footed shot,NaN,Direct free kick,Right-footed shot,Right-footed shot,Header,Right-footed shot,...,Left-footed shot,Penalty,Left-footed shot,Right-footed shot,Penalty,Right-footed shot,Penalty,Left-footed shot,Counter attack goal,Direct free kick
Goal_assist,NaN,Rui Jorge,Carlos Martins,Cesar Prates,NaN,NaN,NaN,NaN,Ryan Giggs,NaN,...,NaN,NaN,Abdulrahman Ghareeb,Sami Al-Najei,NaN,NaN,\t,Sultan Al-Ghannam,Ayman Yahya,NaN

In [ ]:
df_csv.sort_index(axis=1, ascending=False)

,Venue,Type,Season,Result,Playing_Position,Opponent,Minute,Matchday,Goal_assist,Date,Competition,Club,At_score
0,H,Solo run,02/03,3:00,LW,Moreirense FC,34,6,NaN,10-07-02,Liga Portugal,Sporting CP,2:00
1,H,Header,02/03,3:00,LW,Moreirense FC,90+5,6,Rui Jorge,10-07-02,Liga Portugal,Sporting CP,3:00
2,A,Right-footed shot,02/03,1:02,NaN,Boavista FC,88,8,Carlos Martins,10/26/02,Liga Portugal,Sporting CP,1:02
3,H,Left-footed shot,02/03,4:01,NaN,CD Estarreja,67,Fourth Round,Cesar Prates,11/24/02,Taca de Portugal Placard,Sporting CP,3:00
4,H,NaN,02/03,8:01,NaN,FC Oliveira do Hospital,13,Fifth Round,NaN,12/18/02,Taca de Portugal Placard,Sporting CP,3:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,A,Right-footed shot,22/23,0:4,CF,Al-Wehda FC,61,16,NaN,2/9/23,Saudi Pro League,Al-Nassr FC,0:4
706,A,Penalty,22/23,0:3,CF,Damac FC,18,18,\t,2/25/23,Saudi Pro League,Al-Nassr FC,0:1
707,A,Left-footed shot,22/23,0:3,CF,Damac FC,23,18,Sultan Al-Ghannam,2/25/23,Saudi Pro League,Al-Nassr FC,0:2
708,A,Counter attack goal,22/23,0:3,CF,Damac FC,44,18,Ayman Yahya,2/25/23,Saudi Pro League,Al-Nassr FC,0:3
709,H,Direct free kick,22/23,2:1,CF,Abha Club,78,21,NaN,3/18/23,Saudi Pro League,Al-Nassr FC,1:1

In [ ]:
df_csv.shape

(710, 13)

null and their sum

In [ ]:
df_csv.isnull().sum()

Season                0
Competition           0
Matchday              0
Date                  0
Venue                 0
Club                  0
Opponent              0
Result                0
Playing_Position     58
Minute                0
At_score              0
Type                 15
Goal_assist         246
dtype: int64

info of data

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            710 non-null    object
 1   Competition       710 non-null    object
 2   Matchday          710 non-null    object
 3   Date              710 non-null    object
 4   Venue             710 non-null    object
 5   Club              710 non-null    object
 6   Opponent          710 non-null    object
 7   Result            710 non-null    object
 8   Playing_Position  652 non-null    object
 9   Minute            710 non-null    object
 10  At_score          710 non-null    object
 11  Type              695 non-null    object
 12  Goal_assist       464 non-null    object
dtypes: object(13)
memory usage: 72.2+ KB

only selected coloumn

In [ ]:
df_csv[['Season', 'Matchday']]

    Season      Matchday
0    02/03             6
1    02/03             6
2    02/03             8
3    02/03  Fourth Round
4    02/03   Fifth Round
..     ...           ...
705  22/23            16
706  22/23            18
707  22/23            18
708  22/23            18
709  22/23            21

[710 rows x 2 columns]

only selected rows

In [ ]:
df_csv.iloc[3]

Season                                 02/03
Competition         Taca de Portugal Placard
Matchday                        Fourth Round
Date                                11/24/02
Venue                                      H
Club                             Sporting CP
Opponent                        CD Estarreja
Result                                  4:01
Playing_Position                         NaN
Minute                                    67
At_score                                3:00
Type                        Left-footed shot
Goal_assist                     Cesar Prates
Name: 3, dtype: object

In [ ]:
df_csv.iloc[3:5, 0:2]

  Season               Competition
3  02/03  Taca de Portugal Placard
4  02/03  Taca de Portugal Placard

In [ ]:
df_csv.iloc[[1, 2, 4], [0, 2]]

  Season     Matchday
1  02/03            6
2  02/03            8
4  02/03  Fifth Round

In [ ]:
df_csv.iloc[1:3, :]

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins

In [ ]:
df_csv.iloc[:, 1:3]

                  Competition      Matchday
0               Liga Portugal             6
1               Liga Portugal             6
2               Liga Portugal             8
3    Taca de Portugal Placard  Fourth Round
4    Taca de Portugal Placard   Fifth Round
..                        ...           ...
705          Saudi Pro League            16
706          Saudi Pro League            18
707          Saudi Pro League            18
708          Saudi Pro League            18
709          Saudi Pro League            21

[710 rows x 2 columns]

In [ ]:
df_csv.iloc[0:5]

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN

Sorting

In [ ]:
df_csv.sort_values(by='Minute', ascending=False)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
501,16/17,FIFA Club World Cup,Final,12/18/16,H,Real Madrid,Kashima Antlers,4:2 AET,LW,97,3:02,Left-footed shot,Karim Benzema
569,17/18,UEFA Champions League,Quarter-Finals,04-11-18,H,Real Madrid,Juventus FC,1:03,CF,90+7,1:03,Penalty,NaN
606,19/20,Serie A,10,10/30/19,H,Juventus FC,Genoa CFC,2:01,CF,90+6,2:01,Penalty,NaN
332,13/14,LaLiga,6,9/25/13,A,Real Madrid,Elche CF,1:02,LW,90+6,1:02,Penalty,NaN
678,21/22,UEFA Champions League,Group Stage,9/29/21,H,Manchester United,Villarreal CF,2:01,CF,90+5,2:01,Right-footed shot,Jesse Lingard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,10/11,LaLiga,18,01-09-11,H,Real Madrid,Villarreal CF,4:02,LW,10,1:01,Right-footed shot,Mesut Ozil
35,06/07,Premier League,11,11-04-06,H,Manchester United,Portsmouth FC,3:00,RW,10,2:00,Direct free kick,NaN
354,13/14,LaLiga,20,1/18/14,A,Real Madrid,Real Betis Balompie,0:05,LW,10,0:01,Right-footed shot,Angel Di Maria
231,11/12,LaLiga,17,12/17/11,A,Real Madrid,Sevilla FC,2:06,LW,10,0:01,Right-footed shot,Angel Di Maria
127,09/10,LaLiga,3,9/20/09,H,Real Madrid,Xerez CD,5:00,RW,1,1:00,Right-footed shot,NaN

In [ ]:
df_csv[df_csv["Minute"] > "45"]

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
5,03/04,Premier League,11,11-01-03,H,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN
6,03/04,FA Cup,Fifth Round,2/14/04,H,Manchester United,Manchester City,4:02,RW,74,3:00,Right-footed shot,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,22/23,Europa League,Group Stage,10/27/22,H,Manchester United,FC Sheriff,3:0,CF,81,3:0,Left-footed shot,NaN
701,22/23,Saudi Pro League,15,2/3/23,A,Al-Nassr FC,Al-Fateh,2:2,CF,90+3,2:2,Penalty,NaN
704,22/23,Saudi Pro League,16,2/9/23,A,Al-Nassr FC,Al-Wehda FC,0:4,CF,53,0:3,Penalty,NaN
705,22/23,Saudi Pro League,16,2/9/23,A,Al-Nassr FC,Al-Wehda FC,0:4,CF,61,0:4,Right-footed shot,NaN
709,22/23,Saudi Pro League,21,3/18/23,H,Al-Nassr FC,Abha Club,2:1,CF,78,1:1,Direct free kick,NaN

In [ ]:
df = df_csv.copy()

In [ ]:
df_csv.describe()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
count,710,710,710,710,710,710,710,710,652,710,710,695,464
unique,21,17,52,468,2,5,129,57,5,106,43,11,91
top,14/15,LaLiga,Group Stage,09-12-15,H,Real Madrid,Sevilla FC,3:00,LW,90,1:00,Right-footed shot,Karim Benzema
freq,61,311,75,5,404,450,27,49,356,17,111,253,44

Unique elements

In [ ]:
df_csv['Minute'].unique()

array(['34', '90+5', '88', '67', '13', '80', '74', '89', '60', '4', '44',
       '87', '9', '8', '54', '58', '45+1', '21', '76', '63', '90', '12',
       '68', '14', '38', '45', '59', '23', '19', '73', '82', '10', '39',
       '84', '85', '47', '50', '77', '49', '28', '5', '62', '51', '41',
       '35', '90+3', '22', '81', '48', '70', '90+2', '69', '56', '79',
       '16', '53', '3', '24', '32', '26', '25', '30', '43', '65', '11',
       '6', '57', '61', '17', '27', '1', '75', '2', '64', '71', '18',
       '78', '29', '36', '15', '55', '86', '90+1', '72', '20', '42',
       '103', '46', '52', '90+4', '37', '66', '90+6', '31', '40', '120',
       '83', '7', '33', '97', '104', '105', '109', '90+7', '45+7', '45+2'],
      dtype=object)

count of unique elements

In [ ]:
df_csv['Minute'].value_counts()

Minute
90      17
89      15
45      15
23      15
76      14
        ..
105      1
109      1
90+7     1
45+7     1
45+2     1
Name: count, Length: 106, dtype: int64

data types

In [ ]:
df_csv.dtypes

Season              object
Competition         object
Matchday            object
Date                object
Venue               object
Club                object
Opponent            object
Result              object
Playing_Position    object
Minute              object
At_score            object
Type                object
Goal_assist         object
dtype: object

In [ ]:
df_csv.Type

0                 Solo run
1                   Header
2        Right-footed shot
3         Left-footed shot
4                      NaN
              ...
705      Right-footed shot
706                Penalty
707       Left-footed shot
708    Counter attack goal
709       Direct free kick
Name: Type, Length: 710, dtype: object

In [ ]:
df.fillna(value=0)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,0
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,0,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,0,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,0,13,3:00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,22/23,Saudi Pro League,16,2/9/23,A,Al-Nassr FC,Al-Wehda FC,0:4,CF,61,0:4,Right-footed shot,0
706,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,18,0:1,Penalty,\t
707,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,23,0:2,Left-footed shot,Sultan Al-Ghannam
708,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,44,0:3,Counter attack goal,Ayman Yahya
709,22/23,Saudi Pro League,21,3/18/23,H,Al-Nassr FC,Abha Club,2:1,CF,78,1:1,Direct free kick,0

changing datatypes

In [ ]:
df_csv['Type'] = df_csv['Type'].astype(str)