<a href="https://colab.research.google.com/github/PranavPanure/ML-sem2/blob/main/Assignment2_ML_53.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Pranav Panure

Class: CSAI

Div: D

Roll NO: 53

PRN: 12411151

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Rahul","Priya","Amit","Sneha","Rohan","Rohan",
             "Anjali","Karan","Meena","Arjun",
             "Divya","Sameer","Pooja","Akash","Nisha",
             "John","Simran","Vikas",None,"Ritu"],

    "Age": [19,18,None,20,19,19,21,22,20,19,
            18,20,19,23,18,"twenty",21,20,19,22],

    "Gender": ["Male","Female","Male","Female","Male","Male",
               "female","Male","FEMALE","Male",
               "Female","Male","Female","Male","Female",
               "Male","Female","Male","Male","Female"],

    "Attendance": [85,90,75,95,60,60,80,50,92,110,
                   88,40,78,65,82,70,None,55,80,90],

    "Marks": [78,88,65,None,45,45,72,30,91,85,
              79,-10,68,55,73,60,85,40,75,95],

    "Study_Hours": [3.5,4.0,2.5,5.0,1.5,1.5,3.0,1.0,4.8,4.5,
                    3.7,0.5,None,2.0,3.2,2.5,4.2,1.2,3.4,5.1],

    "Result": ["Pass","Pass","Pass","Pass","Fail","Fail",
               "Pass","Fail","Pass","Pass",
               "Pass","Fail","Pass","Fail","Pass",
               "Pass","Pass","Fail","Pass","Pass"]
})

print(df)

    Student_ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul      19    Male        85.0   78.0          3.5   Pass
1          102   Priya      18  Female        90.0   88.0          4.0   Pass
2          103    Amit    None    Male        75.0   65.0          2.5   Pass
3          104   Sneha      20  Female        95.0    NaN          5.0   Pass
4          105   Rohan      19    Male        60.0   45.0          1.5   Fail
5          106   Rohan      19    Male        60.0   45.0          1.5   Fail
6          107  Anjali      21  female        80.0   72.0          3.0   Pass
7          108   Karan      22    Male        50.0   30.0          1.0   Fail
8          109   Meena      20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun      19    Male       110.0   85.0          4.5   Pass
10         111   Divya      18  Female        88.0   79.0          3.7   Pass
11         112  Sameer      20    Male        40.0  -10.0          0.5   Fail
12         113   Pooja      19  Female        78.0   68.0          NaN   Pass
13         114   Akash      23    Male        65.0   55.0          2.0   Fail
14         115   Nisha      18  Female        82.0   73.0          3.2   Pass
15         116    John  twenty    Male        70.0   60.0          2.5   Pass
16         117  Simran      21  Female         NaN   85.0          4.2   Pass
17         118   Vikas      20    Male        55.0   40.0          1.2   Fail
18         119    None      19    Male        80.0   75.0          3.4   Pass
19         120    Ritu      22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.isna()

    Student_ID   Name    Age  Gender  Attendance  Marks  Study_Hours  Result
0        False  False  False   False       False  False        False   False
1        False  False  False   False       False  False        False   False
2        False  False   True   False       False  False        False   False
3        False  False  False   False       False   True        False   False
4        False  False  False   False       False  False        False   False
5        False  False  False   False       False  False        False   False
6        False  False  False   False       False  False        False   False
7        False  False  False   False       False  False        False   False
8        False  False  False   False       False  False        False   False
9        False  False  False   False       False  False        False   False
10       False  False  False   False       False  False        False   False
11       False  False  False   False       False  False        False   False
12       False  False  False   False       False  False         True   False
13       False  False  False   False       False  False        False   False
14       False  False  False   False       False  False        False   False
15       False  False  False   False       False  False        False   False
16       False  False  False   False        True  False        False   False
17       False  False  False   False       False  False        False   False
18       False   True  False   False       False  False        False   False
19       False  False  False   False       False  False        False   False

In [ ]:
df.notna()

    Student_ID   Name    Age  Gender  Attendance  Marks  Study_Hours  Result
0         True   True   True    True        True   True         True    True
1         True   True   True    True        True   True         True    True
2         True   True  False    True        True   True         True    True
3         True   True   True    True        True  False         True    True
4         True   True   True    True        True   True         True    True
5         True   True   True    True        True   True         True    True
6         True   True   True    True        True   True         True    True
7         True   True   True    True        True   True         True    True
8         True   True   True    True        True   True         True    True
9         True   True   True    True        True   True         True    True
10        True   True   True    True        True   True         True    True
11        True   True   True    True        True   True         True    True
12        True   True   True    True        True   True        False    True
13        True   True   True    True        True   True         True    True
14        True   True   True    True        True   True         True    True
15        True   True   True    True        True   True         True    True
16        True   True   True    True       False   True         True    True
17        True   True   True    True        True   True         True    True
18        True  False   True    True        True   True         True    True
19        True   True   True    True        True   True         True    True

In [ ]:
df.replace(np.nan, 0)

    Student_ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul      19    Male        85.0   78.0          3.5   Pass
1          102   Priya      18  Female        90.0   88.0          4.0   Pass
2          103    Amit       0    Male        75.0   65.0          2.5   Pass
3          104   Sneha      20  Female        95.0    0.0          5.0   Pass
4          105   Rohan      19    Male        60.0   45.0          1.5   Fail
5          106   Rohan      19    Male        60.0   45.0          1.5   Fail
6          107  Anjali      21  female        80.0   72.0          3.0   Pass
7          108   Karan      22    Male        50.0   30.0          1.0   Fail
8          109   Meena      20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun      19    Male       110.0   85.0          4.5   Pass
10         111   Divya      18  Female        88.0   79.0          3.7   Pass
11         112  Sameer      20    Male        40.0  -10.0          0.5   Fail
12         113   Pooja      19  Female        78.0   68.0          0.0   Pass
13         114   Akash      23    Male        65.0   55.0          2.0   Fail
14         115   Nisha      18  Female        82.0   73.0          3.2   Pass
15         116    John  twenty    Male        70.0   60.0          2.5   Pass
16         117  Simran      21  Female         0.0   85.0          4.2   Pass
17         118   Vikas      20    Male        55.0   40.0          1.2   Fail
18         119       0      19    Male        80.0   75.0          3.4   Pass
19         120    Ritu      22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.fillna(0)

    Student_ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul      19    Male        85.0   78.0          3.5   Pass
1          102   Priya      18  Female        90.0   88.0          4.0   Pass
2          103    Amit       0    Male        75.0   65.0          2.5   Pass
3          104   Sneha      20  Female        95.0    0.0          5.0   Pass
4          105   Rohan      19    Male        60.0   45.0          1.5   Fail
5          106   Rohan      19    Male        60.0   45.0          1.5   Fail
6          107  Anjali      21  female        80.0   72.0          3.0   Pass
7          108   Karan      22    Male        50.0   30.0          1.0   Fail
8          109   Meena      20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun      19    Male       110.0   85.0          4.5   Pass
10         111   Divya      18  Female        88.0   79.0          3.7   Pass
11         112  Sameer      20    Male        40.0  -10.0          0.5   Fail
12         113   Pooja      19  Female        78.0   68.0          0.0   Pass
13         114   Akash      23    Male        65.0   55.0          2.0   Fail
14         115   Nisha      18  Female        82.0   73.0          3.2   Pass
15         116    John  twenty    Male        70.0   60.0          2.5   Pass
16         117  Simran      21  Female         0.0   85.0          4.2   Pass
17         118   Vikas      20    Male        55.0   40.0          1.2   Fail
18         119       0      19    Male        80.0   75.0          3.4   Pass
19         120    Ritu      22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.dropna()

    Student_ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul      19    Male        85.0   78.0          3.5   Pass
1          102   Priya      18  Female        90.0   88.0          4.0   Pass
4          105   Rohan      19    Male        60.0   45.0          1.5   Fail
5          106   Rohan      19    Male        60.0   45.0          1.5   Fail
6          107  Anjali      21  female        80.0   72.0          3.0   Pass
7          108   Karan      22    Male        50.0   30.0          1.0   Fail
8          109   Meena      20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun      19    Male       110.0   85.0          4.5   Pass
10         111   Divya      18  Female        88.0   79.0          3.7   Pass
11         112  Sameer      20    Male        40.0  -10.0          0.5   Fail
13         114   Akash      23    Male        65.0   55.0          2.0   Fail
14         115   Nisha      18  Female        82.0   73.0          3.2   Pass
15         116    John  twenty    Male        70.0   60.0          2.5   Pass
17         118   Vikas      20    Male        55.0   40.0          1.2   Fail
19         120    Ritu      22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [ ]:
df.convert_dtypes()

    Student_ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul      19    Male          85     78          3.5   Pass
1          102   Priya      18  Female          90     88          4.0   Pass
2          103    Amit    None    Male          75     65          2.5   Pass
3          104   Sneha      20  Female          95   <NA>          5.0   Pass
4          105   Rohan      19    Male          60     45          1.5   Fail
5          106   Rohan      19    Male          60     45          1.5   Fail
6          107  Anjali      21  female          80     72          3.0   Pass
7          108   Karan      22    Male          50     30          1.0   Fail
8          109   Meena      20  FEMALE          92     91          4.8   Pass
9          110   Arjun      19    Male         110     85          4.5   Pass
10         111   Divya      18  Female          88     79          3.7   Pass
11         112  Sameer      20    Male          40    -10          0.5   Fail
12         113   Pooja      19  Female          78     68         <NA>   Pass
13         114   Akash      23    Male          65     55          2.0   Fail
14         115   Nisha      18  Female          82     73          3.2   Pass
15         116    John  twenty    Male          70     60          2.5   Pass
16         117  Simran      21  Female        <NA>     85          4.2   Pass
17         118   Vikas      20    Male          55     40          1.2   Fail
18         119    <NA>      19    Male          80     75          3.4   Pass
19         120    Ritu      22  Female          90     95          5.1   Pass

In [ ]:
df.dropna()

    Student_ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul      19    Male        85.0   78.0          3.5   Pass
1          102   Priya      18  Female        90.0   88.0          4.0   Pass
4          105   Rohan      19    Male        60.0   45.0          1.5   Fail
5          106   Rohan      19    Male        60.0   45.0          1.5   Fail
6          107  Anjali      21  female        80.0   72.0          3.0   Pass
7          108   Karan      22    Male        50.0   30.0          1.0   Fail
8          109   Meena      20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun      19    Male       110.0   85.0          4.5   Pass
10         111   Divya      18  Female        88.0   79.0          3.7   Pass
11         112  Sameer      20    Male        40.0  -10.0          0.5   Fail
13         114   Akash      23    Male        65.0   55.0          2.0   Fail
14         115   Nisha      18  Female        82.0   73.0          3.2   Pass
15         116    John  twenty    Male        70.0   60.0          2.5   Pass
17         118   Vikas      20    Male        55.0   40.0          1.2   Fail
19         120    Ritu      22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.rename(columns={"Student_ID" : "ID"})

     ID    Name     Age  Gender  Attendance  Marks  Study_Hours Result
0   101   Rahul      19    Male        85.0   78.0          3.5   Pass
1   102   Priya      18  Female        90.0   88.0          4.0   Pass
2   103    Amit    None    Male        75.0   65.0          2.5   Pass
3   104   Sneha      20  Female        95.0    NaN          5.0   Pass
4   105   Rohan      19    Male        60.0   45.0          1.5   Fail
5   106   Rohan      19    Male        60.0   45.0          1.5   Fail
6   107  Anjali      21  female        80.0   72.0          3.0   Pass
7   108   Karan      22    Male        50.0   30.0          1.0   Fail
8   109   Meena      20  FEMALE        92.0   91.0          4.8   Pass
9   110   Arjun      19    Male       110.0   85.0          4.5   Pass
10  111   Divya      18  Female        88.0   79.0          3.7   Pass
11  112  Sameer      20    Male        40.0  -10.0          0.5   Fail
12  113   Pooja      19  Female        78.0   68.0          NaN   Pass
13  114   Akash      23    Male        65.0   55.0          2.0   Fail
14  115   Nisha      18  Female        82.0   73.0          3.2   Pass
15  116    John  twenty    Male        70.0   60.0          2.5   Pass
16  117  Simran      21  Female         NaN   85.0          4.2   Pass
17  118   Vikas      20    Male        55.0   40.0          1.2   Fail
18  119    None      19    Male        80.0   75.0          3.4   Pass
19  120    Ritu      22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.loc[18, "Name"] = "Lalit"
df.loc[15, "Age"] = 20
df.loc[2,"Age"] = 20
df.loc[16,"Attendance"] = 75.0
df.loc[3,"Marks"] = 80.0
df.loc[12,"Study_Hours"] = 4
print(df)

    Student_ID    Name Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul  19    Male        85.0   78.0          3.5   Pass
1          102   Priya  18  Female        90.0   88.0          4.0   Pass
2          103    Amit  20    Male        75.0   65.0          2.5   Pass
3          104   Sneha  20  Female        95.0   80.0          5.0   Pass
4          105   Rohan  19    Male        60.0   45.0          1.5   Fail
5          106   Rohan  19    Male        60.0   45.0          1.5   Fail
6          107  Anjali  21  female        80.0   72.0          3.0   Pass
7          108   Karan  22    Male        50.0   30.0          1.0   Fail
8          109   Meena  20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun  19    Male       110.0   85.0          4.5   Pass
10         111   Divya  18  Female        88.0   79.0          3.7   Pass
11         112  Sameer  20    Male        40.0  -10.0          0.5   Fail
12         113   Pooja  19  Female        78.0   68.0          4.0   Pass
13         114   Akash  23    Male        65.0   55.0          2.0   Fail
14         115   Nisha  18  Female        82.0   73.0          3.2   Pass
15         116    John  20    Male        70.0   60.0          2.5   Pass
16         117  Simran  21  Female        75.0   85.0          4.2   Pass
17         118   Vikas  20    Male        55.0   40.0          1.2   Fail
18         119   Lalit  19    Male        80.0   75.0          3.4   Pass
19         120    Ritu  22  Female        90.0   95.0          5.1   Pass

In [ ]:
df["Marks"] = df["Marks"].mask(df["Marks"] < 0, 35)
print(df)

    Student_ID    Name Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul  19    Male        85.0   78.0          3.5   Pass
1          102   Priya  18  Female        90.0   88.0          4.0   Pass
2          103    Amit  20    Male        75.0   65.0          2.5   Pass
3          104   Sneha  20  Female        95.0   80.0          5.0   Pass
4          105   Rohan  19    Male        60.0   45.0          1.5   Fail
5          106   Rohan  19    Male        60.0   45.0          1.5   Fail
6          107  Anjali  21  female        80.0   72.0          3.0   Pass
7          108   Karan  22    Male        50.0   30.0          1.0   Fail
8          109   Meena  20  FEMALE        92.0   91.0          4.8   Pass
9          110   Arjun  19    Male       110.0   85.0          4.5   Pass
10         111   Divya  18  Female        88.0   79.0          3.7   Pass
11         112  Sameer  20    Male        40.0   35.0          0.5   Fail
12         113   Pooja  19  Female        78.0   68.0          4.0   Pass
13         114   Akash  23    Male        65.0   55.0          2.0   Fail
14         115   Nisha  18  Female        82.0   73.0          3.2   Pass
15         116    John  20    Male        70.0   60.0          2.5   Pass
16         117  Simran  21  Female        75.0   85.0          4.2   Pass
17         118   Vikas  20    Male        55.0   40.0          1.2   Fail
18         119   Lalit  19    Male        80.0   75.0          3.4   Pass
19         120    Ritu  22  Female        90.0   95.0          5.1   Pass

In [ ]:
df["Gender"] = df["Gender"].str.title()
print(df)

    Student_ID    Name Age  Gender  Attendance  Marks  Study_Hours Result
0          101   Rahul  19    Male        85.0   78.0          3.5   Pass
1          102   Priya  18  Female        90.0   88.0          4.0   Pass
2          103    Amit  20    Male        75.0   65.0          2.5   Pass
3          104   Sneha  20  Female        95.0   80.0          5.0   Pass
4          105   Rohan  19    Male        60.0   45.0          1.5   Fail
5          106   Rohan  19    Male        60.0   45.0          1.5   Fail
6          107  Anjali  21  Female        80.0   72.0          3.0   Pass
7          108   Karan  22    Male        50.0   30.0          1.0   Fail
8          109   Meena  20  Female        92.0   91.0          4.8   Pass
9          110   Arjun  19    Male       110.0   85.0          4.5   Pass
10         111   Divya  18  Female        88.0   79.0          3.7   Pass
11         112  Sameer  20    Male        40.0   35.0          0.5   Fail
12         113   Pooja  19  Female        78.0   68.0          4.0   Pass
13         114   Akash  23    Male        65.0   55.0          2.0   Fail
14         115   Nisha  18  Female        82.0   73.0          3.2   Pass
15         116    John  20    Male        70.0   60.0          2.5   Pass
16         117  Simran  21  Female        75.0   85.0          4.2   Pass
17         118   Vikas  20    Male        55.0   40.0          1.2   Fail
18         119   Lalit  19    Male        80.0   75.0          3.4   Pass
19         120    Ritu  22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.describe()

       Student_ID       Name  Attendance      Marks  Study_Hours
count    20.00000  20.000000   20.000000  20.000000    20.000000
mean    110.50000   5.000000   76.000000  67.200000     3.055000
std       5.91608   0.561951   17.084927  19.594844     1.408798
min     101.00000   4.000000   40.000000  30.000000     0.500000
25%     105.75000   5.000000   63.750000  52.500000     1.875000
50%     110.50000   5.000000   79.000000  72.500000     3.300000
75%     115.25000   5.000000   88.500000  81.250000     4.050000
max     120.00000   6.000000  110.000000  95.000000     5.100000

In [ ]:
df["Attendance"] = df["Attendance"].clip(lower=0, upper=100)
print(df)

    Student_ID  Name Age  Gender  Attendance  Marks  Study_Hours Result
0          101     5  19    Male        85.0   78.0          3.5   Pass
1          102     5  18  Female        90.0   88.0          4.0   Pass
2          103     4  20    Male        75.0   65.0          2.5   Pass
3          104     5  20  Female        95.0   80.0          5.0   Pass
4          105     5  19    Male        60.0   45.0          1.5   Fail
5          106     5  19    Male        60.0   45.0          1.5   Fail
6          107     6  21  Female        80.0   72.0          3.0   Pass
7          108     5  22    Male        50.0   30.0          1.0   Fail
8          109     5  20  Female        92.0   91.0          4.8   Pass
9          110     5  19    Male       100.0   85.0          4.5   Pass
10         111     5  18  Female        88.0   79.0          3.7   Pass
11         112     6  20    Male        40.0   35.0          0.5   Fail
12         113     5  19  Female        78.0   68.0          4.0   Pass
13         114     5  23    Male        65.0   55.0          2.0   Fail
14         115     5  18  Female        82.0   73.0          3.2   Pass
15         116     4  20    Male        70.0   60.0          2.5   Pass
16         117     6  21  Female        75.0   85.0          4.2   Pass
17         118     5  20    Male        55.0   40.0          1.2   Fail
18         119     5  19    Male        80.0   75.0          3.4   Pass
19         120     4  22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.sort_values(by="Marks")
print(df)

    Student_ID  Name Age  Gender  Attendance  Marks  Study_Hours Result
0          101     5  19    Male        85.0   78.0          3.5   Pass
1          102     5  18  Female        90.0   88.0          4.0   Pass
2          103     4  20    Male        75.0   65.0          2.5   Pass
3          104     5  20  Female        95.0   80.0          5.0   Pass
4          105     5  19    Male        60.0   45.0          1.5   Fail
5          106     5  19    Male        60.0   45.0          1.5   Fail
6          107     6  21  Female        80.0   72.0          3.0   Pass
7          108     5  22    Male        50.0   30.0          1.0   Fail
8          109     5  20  Female        92.0   91.0          4.8   Pass
9          110     5  19    Male       100.0   85.0          4.5   Pass
10         111     5  18  Female        88.0   79.0          3.7   Pass
11         112     6  20    Male        40.0   35.0          0.5   Fail
12         113     5  19  Female        78.0   68.0          4.0   Pass
13         114     5  23    Male        65.0   55.0          2.0   Fail
14         115     5  18  Female        82.0   73.0          3.2   Pass
15         116     4  20    Male        70.0   60.0          2.5   Pass
16         117     6  21  Female        75.0   85.0          4.2   Pass
17         118     5  20    Male        55.0   40.0          1.2   Fail
18         119     5  19    Male        80.0   75.0          3.4   Pass
19         120     4  22  Female        90.0   95.0          5.1   Pass

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   20 non-null     int64
 1   Name         19 non-null     object
 2   Age          19 non-null     object
 3   Gender       20 non-null     object
 4   Attendance   19 non-null     float64
 5   Marks        19 non-null     float64
 6   Study_Hours  19 non-null     float64
 7   Result       20 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.4+ KB

In [ ]:
df.head()
df.tail()
df.sample()

   Student_ID   Name Age Gender  Attendance  Marks  Study_Hours Result
0         101  Rahul  19   Male        85.0   78.0          3.5   Pass

In [ ]:
numeric_df = df.select_dtypes(include='number')
numeric_df.mean()

Student_ID     110.500000
Attendance      76.052632
Marks           64.157895
Study_Hours      3.005263
dtype: float64

In [ ]:
numeric_df.std()

Student_ID      5.916080
Attendance     17.551428
Marks          25.688872
Study_Hours     1.429248
dtype: float64

In [ ]:
numeric_df.min()

Student_ID     101.0
Attendance      40.0
Marks          -10.0
Study_Hours      0.5
dtype: float64

In [ ]:
numeric_df.max()

Student_ID     120.0
Attendance     110.0
Marks           95.0
Study_Hours      5.1
dtype: float64

In [ ]:
df1 = df.copy()
df2 = df.copy()
merged = pd.merge(df1, df2, on="Student_ID", how="inner")
print(merged)

    Student_ID  Name_x   Age_x Gender_x  Attendance_x  Marks_x  Study_Hours_x  \
0          101   Rahul      19     Male          85.0     78.0            3.5
1          102   Priya      18   Female          90.0     88.0            4.0
2          103    Amit    None     Male          75.0     65.0            2.5
3          104   Sneha      20   Female          95.0      NaN            5.0
4          105   Rohan      19     Male          60.0     45.0            1.5
5          106   Rohan      19     Male          60.0     45.0            1.5
6          107  Anjali      21   female          80.0     72.0            3.0
7          108   Karan      22     Male          50.0     30.0            1.0
8          109   Meena      20   FEMALE          92.0     91.0            4.8
9          110   Arjun      19     Male         110.0     85.0            4.5
10         111   Divya      18   Female          88.0     79.0            3.7
11         112  Sameer      20     Male          40.0    -10.0            0.5
12         113   Pooja      19   Female          78.0     68.0            NaN
13         114   Akash      23     Male          65.0     55.0            2.0
14         115   Nisha      18   Female          82.0     73.0            3.2
15         116    John  twenty     Male          70.0     60.0            2.5
16         117  Simran      21   Female           NaN     85.0            4.2
17         118   Vikas      20     Male          55.0     40.0            1.2
18         119    None      19     Male          80.0     75.0            3.4
19         120    Ritu      22   Female          90.0     95.0            5.1

   Result_x  Name_y   Age_y Gender_y  Attendance_y  Marks_y  Study_Hours_y  \
0      Pass   Rahul      19     Male          85.0     78.0            3.5
1      Pass   Priya      18   Female          90.0     88.0            4.0
2      Pass    Amit    None     Male          75.0     65.0            2.5
3      Pass   Sneha      20   Female          95.0      NaN            5.0
4      Fail   Rohan      19     Male          60.0     45.0            1.5
5      Fail   Rohan      19     Male          60.0     45.0            1.5
6      Pass  Anjali      21   female          80.0     72.0            3.0
7      Fail   Karan      22     Male          50.0     30.0            1.0
8      Pass   Meena      20   FEMALE          92.0     91.0            4.8
9      Pass   Arjun      19     Male         110.0     85.0            4.5
10     Pass   Divya      18   Female          88.0     79.0            3.7
11     Fail  Sameer      20     Male          40.0    -10.0            0.5
12     Pass   Pooja      19   Female          78.0     68.0            NaN
13     Fail   Akash      23     Male          65.0     55.0            2.0
14     Pass   Nisha      18   Female          82.0     73.0            3.2
15     Pass    John  twenty     Male          70.0     60.0            2.5
16     Pass  Simran      21   Female           NaN     85.0            4.2
17     Fail   Vikas      20     Male          55.0     40.0            1.2
18     Pass    None      19     Male          80.0     75.0            3.4
19     Pass    Ritu      22   Female          90.0     95.0            5.1

   Result_y
0      Pass
1      Pass
2      Pass
3      Pass
4      Fail
5      Fail
6      Pass
7      Fail
8      Pass
9      Pass
10     Pass
11     Fail
12     Pass
13     Fail
14     Pass
15     Pass
16     Pass
17     Fail
18     Pass
19     Pass